### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by rossant** [kwikteam/phyui#4]
- [x] Remove unnecessary files in the root
- [x] Update README
- [x] Update `.travis.yml`: no need for tests for now (we'll need to think about how to automatically test the JS, the widgets, and the notebook)
- [x] remove `phyui/plot`
- [x] clean up obsolete JS injection in `phyui/utils`
- [x] use underscore instead of camelCase in the Python code
- [x] put the test files in a new `tests/` folder
- [x] move `static/phyui` to `phyui/static/`
- [x] reorganize the code into:
  - `phyui/static/`: HTML and build scripts
  - `phyui/static/js/`: our own JS code
  - `phyui/static/js/lib/`: d3.js and dock-spawn submodule
  - `phyui/static/css/`: CSS files
- [x] clean up `phyui/session`
- [x] put back travis with linter

**Comment by cgestes** [comment]
I dont plan to do the followings:
- moving static around.
- use camelCase in JS. (feel free to reformat code, I think its a lost of time when the code is already coherent enough)

Status I dont know:
- cleanup session.
